import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Link from "next/link";
import { ArrowRight, BarChart3, ChevronRight, Search, ShieldCheck } from "lucide-react";
const listingCategories = [
    { title: "Rooms", href: "/properties?type=ROOM", copy: "Shared and private room inventory." },
    { title: "Flats", href: "/properties?type=FLAT", copy: "1, 2 and 3 BHK rental listings." },
    { title: "PG / Hostel", href: "/properties?type=PG", copy: "Girls and boys PG inventory." },
    { title: "Commercial", href: "/contact", copy: "Office and shop requirements." }
];
const serviceCards = [
    { icon: Search, title: "Search", copy: "Filter by locality, budget, furnishing, and occupancy." },
    { icon: ShieldCheck, title: "Verified", copy: "Focus on direct owners and clean property records." },
    { icon: BarChart3, title: "Track", copy: "Save listings, compare options, and review activity." }
];
const metrics = [
    { label: "Active listings", value: "2,400+" },
    { label: "Covered districts", value: "36" },
    { label: "Saved searches", value: "Fast alerts" }
];
function SectionLabel({ children }) {
    return _jsx("div", { className: "landing-eyebrow w-fit", children: children });
}
function HeroMockup() {
    return (_jsxs("div", { className: "surface-card overflow-hidden p-5 md:p-6", children: [_jsxs("div", { className: "flex items-center justify-between gap-4 border-b border-[rgba(15,23,42,0.08)] pb-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-[0.2em] text-[var(--rf-cyan)]", children: "Live workspace" }), _jsx("p", { className: "mt-2 text-lg font-bold", children: "Rental operations dashboard" })] }), _jsx("span", { className: "pill-badge px-3 py-1 text-xs", children: "8 active listings" })] }), _jsxs("div", { className: "mt-4 grid gap-4 sm:grid-cols-2", children: [_jsxs("div", { className: "surface-card p-4", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.16em] text-[var(--rf-muted)]", children: "Monthly rent" }), _jsx("p", { className: "mt-3 text-3xl font-bold text-[var(--rf-cyan)]", children: "Rs. 1,20,000" }), _jsx("p", { className: "mt-2 text-sm text-[var(--rf-muted)]", children: "Collected across active properties." })] }), _jsxs("div", { className: "surface-card p-4", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.16em] text-[var(--rf-muted)]", children: "Pending alerts" }), _jsx("p", { className: "mt-3 text-3xl font-bold text-[var(--rf-cyan)]", children: "12" }), _jsx("p", { className: "mt-2 text-sm text-[var(--rf-muted)]", children: "Payments, renewals, and follow-ups." })] })] }), _jsxs("div", { className: "mt-4 flex items-center justify-between gap-3 border-t border-[rgba(15,23,42,0.08)] pt-4", children: [_jsx("p", { className: "text-sm text-[var(--rf-muted)]", children: "Recent activity: enquiry received, reminder sent, listing updated." }), _jsxs(Link, { href: "/properties", className: "inline-flex items-center gap-2 text-sm font-semibold text-[var(--rf-cyan)]", children: ["Open listings", _jsx(ChevronRight, { className: "size-4" })] })] })] }));
}
export default function HomePage() {
    return (_jsxs("div", { className: "page-shell py-8 md:py-10", children: [_jsx("section", { className: "landing-hero reveal-up", children: _jsxs("div", { className: "grid gap-10 lg:grid-cols-[1.02fr_0.98fr] lg:items-center", children: [_jsxs("div", { className: "space-y-6", children: [_jsx(SectionLabel, { children: "Real estate rent tracking system" }), _jsxs("div", { children: [_jsx("p", { className: "text-sm uppercase tracking-[0.24em] text-[var(--rf-cyan)]", children: "RentFlow" }), _jsx("h1", { className: "mt-3 max-w-xl text-5xl font-bold leading-tight md:text-7xl", children: "A focused rental platform for Maharashtra." })] }), _jsx("p", { className: "max-w-xl text-sm leading-7 text-[var(--rf-muted)] md:text-base", children: "Built with a consistent light UI, clear navigation, aligned forms, and a compact dashboard experience." }), _jsxs("div", { className: "flex flex-wrap gap-3", children: [_jsxs(Link, { href: "/properties", className: "landing-primary-button", children: ["Explore properties", _jsx(ArrowRight, { className: "size-4" })] }), _jsx(Link, { href: "/register", className: "landing-secondary-button", children: "Get started" })] }), _jsx("p", { className: "text-sm uppercase tracking-[0.24em] text-[var(--rf-muted)]", children: "Trusted rental operations for Maharashtra" }), _jsx("div", { className: "grid gap-3 pt-2 sm:grid-cols-3", children: metrics.map((item) => (_jsxs("div", { className: "surface-card p-4", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.18em] text-[var(--rf-muted)]", children: item.label }), _jsx("p", { className: "mt-2 text-lg font-bold text-[var(--rf-cyan)]", children: item.value })] }, item.label))) })] }), _jsx(HeroMockup, {})] }) }), _jsxs("section", { id: "properties", className: "mt-16 scroll-mt-32 reveal-up", children: [_jsx("div", { className: "flex items-end justify-between gap-4", children: _jsxs("div", { children: [_jsx(SectionLabel, { children: "Properties" }), _jsx("h2", { className: "mt-4 text-3xl font-bold md:text-4xl", children: "Browse the core inventory paths." })] }) }), _jsx("div", { className: "mt-4 grid gap-4 md:grid-cols-2 xl:grid-cols-4", children: listingCategories.map((item) => (_jsxs(Link, { href: item.href, className: "surface-card block p-5", children: [_jsx("p", { className: "text-lg font-bold", children: item.title }), _jsx("p", { className: "mt-3 text-sm leading-7 text-[var(--rf-muted)]", children: item.copy }), _jsxs("span", { className: "mt-5 inline-flex items-center gap-2 text-sm font-semibold text-[var(--rf-cyan)]", children: ["Browse", _jsx(ChevronRight, { className: "size-4" })] })] }, item.title))) })] }), _jsxs("section", { id: "services", className: "mt-16 scroll-mt-32 reveal-up", children: [_jsx(SectionLabel, { children: "Services" }), _jsx("div", { className: "mt-4 grid gap-4 md:grid-cols-3", children: serviceCards.map((item) => {
                            const Icon = item.icon;
                            return (_jsxs("div", { className: "surface-card p-5", children: [_jsx("span", { className: "flex size-11 items-center justify-center border border-[rgba(15,118,110,0.18)] bg-[rgba(15,118,110,0.08)] text-[var(--rf-cyan)]", children: _jsx(Icon, { className: "size-5" }) }), _jsx("p", { className: "mt-4 text-lg font-bold", children: item.title }), _jsx("p", { className: "mt-3 text-sm leading-7 text-[var(--rf-muted)]", children: item.copy })] }, item.title));
                        }) })] }), _jsx("section", { className: "mt-16 reveal-up", children: _jsxs("div", { className: "grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center", children: [_jsxs("div", { className: "surface-card p-6", children: [_jsx("h3", { className: "text-2xl font-bold", children: "Production UI, stripped to the essentials." }), _jsx("p", { className: "mt-2 max-w-2xl text-sm leading-7 text-[var(--rf-muted)]", children: "The homepage keeps only the sections that support a real product flow and matches the same light system used across the app." })] }), _jsxs(Link, { href: "/contact", className: "landing-primary-button", children: ["Contact us", _jsx(ArrowRight, { className: "size-4" })] })] }) })] }));
}
