"use client";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Building2, CheckCircle2, LockKeyhole } from "lucide-react";
export function AuthCard({ title, description, children }) {
    const pathname = usePathname();
    return (_jsxs("div", { className: "auth-shell", children: [_jsx("div", { className: "auth-side", style: {
                    ["--rf-hero-image"]: "linear-gradient(180deg, rgba(255,255,255,0.18), rgba(248,250,252,0.96)), radial-gradient(circle at 18% 8%, rgba(15,118,110,0.14), transparent 26%), linear-gradient(135deg, #ffffff, #eef3f8)"
                }, children: _jsxs("div", { className: "relative z-10 flex h-full flex-col justify-between", children: [_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "landing-pill", children: [_jsx(Building2, { className: "size-4" }), "RentFlow"] }), _jsxs("div", { className: "space-y-4", children: [_jsx("h2", { className: "max-w-lg text-4xl font-bold leading-tight text-[var(--rf-ink)]", children: "A clean login surface for owners, tenants, and admins." }), _jsx("p", { className: "max-w-lg text-sm leading-7 text-[var(--rf-muted)]", children: "The auth flow uses the same system language as the rest of the app, without extra marketing panels or redundant UI." })] })] }), _jsxs("div", { className: "grid gap-3", children: [_jsx("div", { className: "surface-card p-4", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "landing-icon", children: _jsx(CheckCircle2, { className: "size-5" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-bold", children: "Verified account flow" }), _jsx("p", { className: "mt-1 text-sm leading-6 text-[var(--rf-muted)]", children: "Consistent sign-in and sign-up validation." })] })] }) }), _jsx("div", { className: "surface-card p-4", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "landing-icon", children: _jsx(LockKeyhole, { className: "size-5" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-bold", children: "Secure access" }), _jsx("p", { className: "mt-1 text-sm leading-6 text-[var(--rf-muted)]", children: "Single route for protected workspace access." })] })] }) })] })] }) }), _jsxs("div", { className: "p-4 sm:p-8", children: [_jsx("div", { className: "auth-tab-shell", children: _jsxs("div", { className: "mx-auto flex w-fit items-center gap-1", children: [_jsx(Link, { href: "/login", className: `auth-tab ${pathname === "/login" ? "auth-tab-active" : ""}`, children: "Login" }), _jsx(Link, { href: "/register", className: `auth-tab ${pathname === "/register" ? "auth-tab-active" : ""}`, children: "Register" })] }) }), _jsxs("div", { className: "px-2 pb-2 pt-8 sm:px-4", children: [_jsxs("div", { className: "flex items-center gap-2 text-xs uppercase tracking-[0.22em] text-[var(--rf-cyan)]", children: [_jsx(LockKeyhole, { className: "size-4" }), "Secure access"] }), _jsx("h1", { className: "mt-4 text-3xl font-bold", children: title }), _jsx("p", { className: "mt-2 max-w-xl text-sm leading-7 text-[var(--rf-muted)]", children: description }), _jsx("div", { className: "mt-8", children: children })] })] })] }));
}
